### ISSUE TITLE
The screenshot is not available

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.kiwix.desktop#1]
![captura de tela de 2019-01-30 19-47-42](https://user-images.githubusercontent.com/26097419/52014940-9776a780-24bf-11e9-96be-ede54cda871d.png)

**Comment by hadess** [comment]
That's because there's no screenshot in the upstream appdata:
https://github.com/kiwix/kiwix-desktop/blob/master/resources/org.kiwix.desktop.appdata.xml

**Comment by hadess** [comment]
See also https://github.com/kiwix/kiwix-desktop/issues/102
