### ISSUE TITLE
bad response and keyboard experience

### ISSUE THREAD

**Issue by ynikitenko** [flathub/org.kiwix.desktop#5]
I installed the recent version using `flatpak install flathub org.kiwix.desktop` (in fact the problem was present in my previous installation as well).
When I used Kiwix several years ago, it required me to choose the zim library (I couldn't use two simultaneously). Then I could type Ctrl+L as in a browser and type the word I wanted to find.
Now Ctrl+L doesn't work in the application. I have to draw the cursor to the search bar and activate that. 
In the settings I don't have any shortcut for searchbar.

But this is not the only problem. When I type, for example, `user` in the search bar (I loaded wiktionary), below that appear several suggestions (the first one being `userer`). When I type `user` and press Enter, `userer` is opened, which is not appropriate.
Pretty often, even when I press `user` with mouse from the suggestion list, it doesn't open the article. I have to close Kiwix and open that again, and then it works.

I'm not sure whether it is connected to the flathub version. I tried to install from source, but failed yet. If there is really some core limitation in the flathub version, please write about that in its README.

I'm using Gnome desktop on Fedora Core 29.

**Comment by mgautierfr** [comment]
Issue moved to kiwix/kiwix-desktop#395
